# Generated by Django 4.2.1 on 2023-05-22 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_by', models.CharField(max_length=100, null=True)),
                ('comment_body', models.TextField(null=True)),
                ('comment_date', models.DateField(default=datetime.datetime.now)),
                ('comment_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='home.post')),
            ],
        ),
    ]
