# Generated by Django 4.2.1 on 2023-05-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_on', models.CharField(max_length=100)),
                ('liked_by', models.CharField(max_length=100)),
            ],
        ),
    ]
