# Generated by Django 4.2.1 on 2023-05-23 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_by', models.CharField(max_length=100)),
                ('reply_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='home.comment')),
            ],
        ),
    ]
