# Generated by Django 4.2.1 on 2023-05-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_post_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='person',
        ),
    ]
