# Generated by Django 4.2.1 on 2023-05-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_by', models.CharField(max_length=100, null=True)),
                ('followed_to', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
